### ISSUE TITLE
Startup error...

### ISSUE THREAD

**Issue by danielbrunt57** [marthoc/homeseer#46]
I am seeing this in HA log at startup.  Curious what it is complaining about.  A timeout of some sort?  Integration seems to work fine though...

```
Logger: libhomeseer.listener
Source: /usr/local/lib/python3.8/site-packages/libhomeseer/listener.py:82
First occurred: 12:43:21 AM (1 occurrences)
Last logged: 12:43:21 AM

Failed to login to HomeSeer ASCII at 192.168.1.103:11000: DC,769,12968148.304839,12968147.504409
```

**Comment by marthoc** [comment]
Interesting! Not a timeout. When the listener first connects to the ASCII connection, it attempts to log in using the provided username and password because otherwise the HomeSeer log throws continuous "unauthorized" errors. The login function expects an "OK" response. The problem is that over telnet the responses can be out of order - in this case, while listening for a response to the login request, HS has sent a device change update. If the login is unsuccessful, we try again until successful, so the next login clearly was successful and the system went on working. Nothing to worry about, but it does suggest that section of listener code could be structured differently to catch out-of-order responses.
