### ISSUE TITLE
Entity Name Template

### ISSUE THREAD

**Issue by davidrule1969** [marthoc/homeseer#48]
I've left the entity name template at its default setting of "{{ device.location2 }} {{ device.location }} {{ device.name }}" and it works for most HS devices but I've got a couple of devices that look like they are coming in as "{{ device.location2 }} {{ device.location }} {{ device.featurename }}".  They have the Feature name instead of Device name.  This isn't a huge problem, I can rename them, but I can't see why this is happening.  The device names are unique but the feature names aren't.

David

**Comment by marthoc** [comment]
This is happening because at the API level, HS treats each feature as a separate device. So, when this integration reads the API response, it creates a separate entity for each feature, and names them according to the name of the feature. This is partly down to how HS4 displays things in its UI which makes it seem like you have one device with a bunch of features. But under the hood at the JSON API level its the same as HS3 in terms of root device/child devices.

**Comment by danielbrunt57** [comment]
> This is happening because at the API level, HS treats each feature as a separate device. So, when this integration reads the API response, it creates a separate entity for each feature, and names them according to the name of the feature. This is partly down to how HS4 displays things in its UI which makes it seem like you have one device with a bunch of features. But under the hood at the JSON API level its the same as HS3 in terms of root device/child devices.

HS4 is just a new body shell on top of the same old chassis...
